---
- name: User Playbook
  become: yes
  become_method: sudo
  user: centos
  hosts: all
  tasks:
  - name: Add users
    user:
      name: "{{item}}"
      state: present
    with_items:
    - bob
    - lisa
    - tom
    - mat
