---
- name: Installs packages
  become: yes
  become_method: sudo
  user: centos
  hosts: all
  tasks:
  - name: Install wordpress
    get_url:
      url: https://wordpress.org/latest.tar.gz
      dest: /var/www/html/

    unarchive:
      src: latest.tar.gz
      dest: /var/www/html/
      remote_src: yes

    copy:
      src: /var/www/html/wordpress/*
      dest: /var/www/html/
      owner: apache
      group: apache